# Generated by Django 3.2.9 on 2022-03-13 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Укажите корректное время приготовления!')], verbose_name='Время приготовления'),
        ),
    ]
